HNEE-697 Add German translations for the labels
fgtclb/academic-persons pull request #16
Opened 2024-01-25 12:45 UTC by Hamza2961

2024-01-30 09:06 UTC, torben-fr requested changes

2024-01-30 09:06 UTC, torben-fr commented on Resources/Private/Language/de.locallang_be.xlf
> +                <target>Liste der Profile</target>
I would change "der" to "von"

2024-01-30 09:06 UTC, torben-fr commented on Resources/Private/Language/de.locallang_tca.xlf
> +                <target>Straße Nummer</target>
That would be "Hausnummer" in German

2024-01-30 09:06 UTC, torben-fr commented on Resources/Private/Language/de.locallang_tca.xlf
> +                <target>divers</target>
With a capital "D" please

2024-01-30 09:06 UTC, torben-fr commented on Resources/Private/Language/de.locallang_tca.xlf
> +                <target>Mittlerer Name</target>
That would be "Zweitname" in German

2024-01-30 09:06 UTC, torben-fr commented on Resources/Private/Language/de.locallang_tca.xlf
> +                <target>E-Mail-Adressen</target>
The second "-" is not needed, please remove it

2024-01-31 09:13 UTC, Riiiad approved these changes

2024-01-31 09:23 UTC, Riiiad approved these changes

2024-01-31 09:23 UTC, torben-fr approved these changes

2024-01-31 09:23 UTC, merged